language: java

script: make build

deploy:
  provider: script
  script: make decrypt && make deploy && make docs
  on:
    tags: true

after_deploy: rm -rf .deploy/keys ; rm .deploy/keys.tar ; rm ${HOME}/.ssh/docs_deploy_key
